import type { Metadata } from "next";
import "./globals.css";
import Headers from "@/app/components/Headers";
import ContextProvider from "@/context/ContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <ContextProvider>
            <Headers />
            {children}
          </ContextProvider>
        </main>
      </body>
    </html>
  );
}
